In [51]:
import pandas as pd

df = pd.read_csv('pokemon_data.csv')

print(df.head(5))

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4  4             Charmander   Fire     NaN  39      52       43       60

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False
4       50     65           1      False

In [52]:
#read headers
print(df.columns)

#read each column
print(df['Name'][0:5]) #or df.Name

print(df[['Name', 'Type 1']][0:5])

#read each row
print(df.iloc[0:4]) #integer location


print(df.loc[df['Type 1'] == 'Fire'])#find specific data that isnt int based - textual info

#read specific location (R,C)
print(df.iloc[2,1]) #row then col

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')
0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object
                    Name Type 1
0              Bulbasaur  Grass
1                Ivysaur  Grass
2               Venusaur  Grass
3  VenusaurMega Venusaur  Grass
4             Charmander   Fire
   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False
       #                       Name Type 1    Type 2   HP  Attack  Defense  \
4      4                 Charmander   Fire       NaN   39      52       43
5      5                 Charmeleon   Fire       NaN   58      64       58
6      6                  Charizard   Fire    Flying   78      84       78
7      6  CharizardMega Charizard X   Fire    Dragon   78     130      111
8      6  CharizardMega Charizard Y   Fire    Flying   78     104       78
42    37                     Vulpix   Fire       NaN   38      41       40
43    38                  Ninetales   Fire       NaN   73      76       75
63    58                  Growlithe   Fire       NaN   55      70       45
64    59                   Arcanine   Fire       NaN   90     110       80
83    77                     Ponyta   Fire       NaN   50      85       55
84    78                   Rapidash   Fire       NaN   65     100       70
135  126                     Magmar   Fire       NaN   65      95       57
147  136                    Flareon   Fire       NaN   65     130       60
158  146                    Moltres   Fire    Flying   90     100       90
169  155                  Cyndaquil   Fire       NaN   39      52       43
170  156                    Quilava   Fire       NaN   58      64       58
171  157                 Typhlosion   Fire       NaN   78      84       78
236  218                     Slugma   Fire       NaN   40      40       40
237  219                   Magcargo   Fire      Rock   50      50      120
259  240                      Magby   Fire       NaN   45      75       37
263  244                      Entei   Fire       NaN  115     115       85
270  250                      Ho-oh   Fire    Flying  106     130       90
276  255                    Torchic   Fire       NaN   45      60       40
277  256                  Combusken   Fire  Fighting   60      85       60
278  257                   Blaziken   Fire  Fighting   80     120       70
279  257      BlazikenMega Blaziken   Fire  Fighting   80     160       80
352  322                      Numel   Fire    Ground   60      60       40
353  323                   Camerupt   Fire    Ground   70     100       70
354  323      CameruptMega Camerupt   Fire    Ground   70     120      100
355  324                    Torkoal   Fire       NaN   70      85      140
435  390                   Chimchar   Fire       NaN   44      58       44
436  391                   Monferno   Fire  Fighting   64      78       52
437  392                  Infernape   Fire  Fighting   76     104       71
518  467                  Magmortar   Fire       NaN   75      95       67
542  485                    Heatran   Fire     Steel   91      90      106
557  498                      Tepig   Fire       NaN   65      63       45
558  499                    Pignite   Fire  Fighting   90      93       55
559  500                     Emboar   Fire  Fighting  110     123       65
572  513                    Pansear   Fire       NaN   50      53       48
573  514                   Simisear   Fire       NaN   75      98       63
614  554                   Darumaka   Fire       NaN   70      90       45
615  555    DarmanitanStandard Mode   Fire       NaN  105     140       55
616  555         DarmanitanZen Mode   Fire   Psychic  105      30      105
692  631                    Heatmor   Fire       NaN   85      97       66
721  653                   Fennekin   Fire       NaN   40      45       40
722  654                    Braixen   Fire       NaN   59      59       58
723  655                    Delphox   Fire   Psychic   75      69       72
730  662                Fletchinder   Fire    Flying   62      73       55
731  663                 Talonflame   Fire    Flying   78      81       71
735  667                     Litleo   Fire    Normal   62      50       58
736  668                     Pyroar   Fire    Normal   86      68       72
799  721                  Volcanion   Fire     Water   80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
4         60       50     65           1      False
5         80       65     80           1      False
6        109       85    100           1      False
7        130       85    100           1      False
8        159      115    100           1      False
42        50       65     65           1      False
43        81      100    100           1      False
63        70       50     60           1      False
64       100       80     95           1      False
83        65       65     90           1      False
84        80       80    105           1      False
135      100       85     93           1      False
147       95      110     65           1      False
158      125       85     90           1       True
169       60       50     65           2      False
170       80       65     80           2      False
171      109       85    100           2      False
236       70       40     20           2      False
237       80       80     30           2      False
259       70       55     83           2      False
263       90       75    100           2       True
270      110      154     90           2       True
276       70       50     45           3      False
277       85       60     55           3      False
278      110       70     80           3      False
279      130       80    100           3      False
352       65       45     35           3      False
353      105       75     40           3      False
354      145      105     20           3      False
355       85       70     20           3      False
435       58       44     61           4      False
436       78       52     81           4      False
437      104       71    108           4      False
518      125       95     83           4      False
542      130      106     77           4       True
557       45       45     45           5      False
558       70       55     55           5      False
559      100       65     65           5      False
572       53       48     64           5      False
573       98       63    101           5      False
614       15       45     50           5      False
615       30       55     95           5      False
616      140      105     55           5      False
692      105       66     65           5      False
721       62       60     60           6      False
722       90       70     73           6      False
723      114      100    104           6      False
730       56       52     84           6      False
731       74       69    126           6      False
735       73       54     72           6      False
736      109       66    106           6      False
799      130       90     70           6       True
Venusaur

In [53]:
#describing data

df.describe() #summary information

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [54]:
#sorting

df.sort_values(['Type 1', 'HP'], ascending = [1, 0])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,4,False
698,637,Volcarona,Bug,Fire,85,60,65,135,105,100,5,False
231,214,Heracross,Bug,Fighting,80,125,75,40,95,85,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
678,617,Accelgor,Bug,NaN,80,70,40,100,60,145,5,False
734,666,Vivillon,Bug,Flying,80,52,50,90,50,89,6,False
447,402,Kricketune,Bug,NaN,77,85,51,55,51,65,4,False
220,205,Forretress,Bug,Steel,75,90,140,60,60,40,2,False
602,542,Leavanny,Bug,Grass,75,103,80,70,80,92,5,False
717,649,Genesect,Bug,Steel,71,120,95,120,95,99,5,False
54,49,Venomoth,Bug,Poison,70,65,60,90,75,90,1,False
132,123,Scyther,Bug,Flying,70,110,80,55,80,105,1,False
182,168,Ariados,Bug,Poison,70,90,70,60,60,40,2,False
228,212,Scizor,Bug,Steel,70,130,100,55,80,65,2,False
229,212,ScizorMega Scizor,Bug,Steel,70,150,140,65,100,75,2,False
308,284,Masquerain,Bug,Flying,70,60,62,80,82,60,3,False
461,414,Mothim,Bug,Flying,70,94,50,94,50,66,4,False
463,416,Vespiquen,Bug,Flying,70,80,102,80,102,40,4,False
619,558,Crustle,Bug,Rock,70,95,125,65,75,45,5,False
650,589,Escavalier,Bug,Steel,70,135,105,60,105,20,5,False
657,596,Galvantula,Bug,Electric,70,77,60,97,60,108,5,False
18,15,Beedrill,Bug,Poison,65,90,40,45,80,75,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,1,False
136,127,Pinsir,Bug,NaN,65,125,100,55,70,85,1,False
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False
208,193,Yanma,Bug,Flying,65,65,45,75,45,95,2,False
342,313,Volbeat,Bug,NaN,65,73,55,47,75,85,3,False
343,314,Illumise,Bug,NaN,65,47,55,73,75,85,3,False
315,291,Ninjask,Bug,Flying,61,90,45,50,50,160,3,False
15,12,Butterfree,Bug,Flying,60,45,50,90,80,70,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
725,657,Frogadier,Water,NaN,54,63,52,83,56,97,6,False
438,393,Piplup,Water,NaN,53,51,53,61,56,40,4,False
59,54,Psyduck,Water,NaN,50,52,48,65,50,55,1,False
98,91,Cloyster,Water,Ice,50,95,180,85,45,70,1,False
172,158,Totodile,Water,NaN,50,65,64,44,48,43,2,False
280,258,Mudkip,Water,NaN,50,70,50,50,50,40,3,False
371,339,Barboach,Water,Ground,50,48,43,46,41,60,3,False
574,515,Panpour,Water,NaN,50,53,48,53,48,64,5,False
595,535,Tympole,Water,NaN,50,50,40,50,40,64,5,False
762,692,Clauncher,Water,NaN,50,53,62,58,63,44,6,False
506,456,Finneon,Water,NaN,49,49,56,49,61,66,4,False
127,118,Goldeen,Water,NaN,45,67,60,35,50,63,1,False
347,318,Carvanha,Water,Dark,45,90,20,65,20,65,3,False
508,458,Mantyke,Water,Flying,45,20,50,60,120,50,4,False
9,7,Squirtle,Water,NaN,44,48,65,50,64,43,1,False
373,341,Corphish,Water,NaN,43,80,65,50,35,35,3,False
405,370,Luvdisc,Water,NaN,43,30,55,40,65,97,3,False
724,656,Froakie,Water,NaN,41,56,40,62,44,71,6,False
65,60,Poliwag,Water,NaN,40,50,40,40,40,90,1,False
78,72,Tentacool,Water,Poison,40,40,35,50,100,70,1,False
293,270,Lotad,Water,Grass,40,30,30,40,50,30,3,False
301,278,Wingull,Water,Flying,40,30,30,55,30,85,3,False
241,223,Remoraid,Water,NaN,35,65,35,65,35,65,2,False
401,366,Clamperl,Water,NaN,35,64,85,74,55,32,3,False
97,90,Shellder,Water,NaN,30,65,100,45,25,40,1,False
106,98,Krabby,Water,NaN,30,105,90,25,25,50,1,False
125,116,Horsea,Water,NaN,30,40,70,70,25,60,1,False
129,120,Staryu,Water,NaN,30,45,55,70,55,85,1,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
381,349,Feebas,Water,NaN,20,15,20,10,55,80,3,False

In [29]:
#changes to the data

#create a total category
df['Total'] = df.iloc[:, 4:10].sum(axis = 1) #axis 1 horizontal

cols = list(df.columns.values)
df = df[cols[0:4] + [cols[-1]] + cols[4:12]]
df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [55]:
#filter data
new_df = df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison')]

#reset index
new_df.reset_index(drop = True, inplace = True)

new_df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False
5,44,Gloom,Grass,Poison,60,65,70,85,75,40,1,False
6,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False
7,69,Bellsprout,Grass,Poison,50,75,35,70,30,40,1,False
8,70,Weepinbell,Grass,Poison,65,90,50,85,45,55,1,False
9,71,Victreebel,Grass,Poison,80,105,65,100,70,70,1,False
10,315,Roselia,Grass,Poison,50,60,45,100,80,65,3,False
11,406,Budew,Grass,Poison,40,30,35,50,70,55,4,False
12,407,Roserade,Grass,Poison,60,70,65,125,105,90,4,False
13,590,Foongus,Grass,Poison,69,55,45,55,55,15,5,False
14,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,5,False

In [43]:
import re

#remove rows with Mega in name
#df.loc[~df['Type 1'].str.contains('Fire|Grass', flags = re.I, regex = True)] 
#~ means not 
# re.I means ignore capitals

df.loc[df['Name'].str.contains('^pi[a-z]*', flags = re.I, regex = True)] 
#starts with PI

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
20,16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,349,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False
30,25,Pikachu,Electric,NaN,320,35,55,40,50,50,90,1,False
136,127,Pinsir,Bug,NaN,500,65,125,100,55,70,85,1,False
137,127,PinsirMega Pinsir,Bug,Flying,600,65,155,120,65,90,105,1,False
186,172,Pichu,Electric,NaN,205,20,40,15,35,35,60,2,False
219,204,Pineco,Bug,NaN,290,50,65,90,35,35,15,2,False
239,221,Piloswine,Ice,Ground,450,100,100,80,60,60,50,2,False
438,393,Piplup,Water,NaN,314,53,51,53,61,56,40,4,False
558,499,Pignite,Fire,Fighting,418,90,93,55,70,55,55,5,False
578,519,Pidove,Normal,Flying,264,50,55,50,36,30,43,5,False

In [48]:
#conditional changes
df.loc[df['Type 1'] == 'Flamer', 'TLenegdary'] = True

df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,TLenegdary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,NaN
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,NaN
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,NaN
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,NaN
4,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,True
5,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,True
6,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,True
7,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,True
8,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,True
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False,NaN
10,8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False,NaN
11,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False,NaN
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False,NaN
13,10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False,NaN
14,11,Metapod,Bug,NaN,205,50,20,55,25,25,30,1,False,NaN
15,12,Butterfree,Bug,Flying,395,60,45,50,90,80,70,1,False,NaN
16,13,Weedle,Bug,Poison,195,40,35,30,20,20,50,1,False,NaN
17,14,Kakuna,Bug,Poison,205,45,25,50,25,25,35,1,False,NaN
18,15,Beedrill,Bug,Poison,395,65,90,40,45,80,75,1,False,NaN
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,NaN
20,16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False,NaN
21,17,Pidgeotto,Normal,Flying,349,63,60,55,50,50,71,1,False,NaN
22,18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,1,False,NaN
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False,NaN
24,19,Rattata,Normal,NaN,253,30,56,35,25,35,72,1,False,NaN
25,20,Raticate,Normal,NaN,413,55,81,60,50,70,97,1,False,NaN
26,21,Spearow,Normal,Flying,262,40,60,30,31,31,70,1,False,NaN
27,22,Fearow,Normal,Flying,442,65,90,65,61,61,100,1,False,NaN
28,23,Ekans,Poison,NaN,288,35,60,44,40,54,55,1,False,NaN
29,24,Arbok,Poison,NaN,438,60,85,69,65,79,80,1,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
770,700,Sylveon,Fairy,NaN,525,95,65,65,110,130,60,6,False,NaN
771,701,Hawlucha,Fighting,Flying,500,78,92,75,74,63,118,6,False,NaN
772,702,Dedenne,Electric,Fairy,431,67,58,57,81,67,101,6,False,NaN
773,703,Carbink,Rock,Fairy,500,50,50,150,50,150,50,6,False,NaN
774,704,Goomy,Dragon,NaN,300,45,50,35,55,75,40,6,False,NaN
775,705,Sliggoo,Dragon,NaN,452,68,75,53,83,113,60,6,False,NaN
776,706,Goodra,Dragon,NaN,600,90,100,70,110,150,80,6,False,NaN
777,707,Klefki,Steel,Fairy,470,57,80,91,80,87,75,6,False,NaN
778,708,Phantump,Ghost,Grass,309,43,70,48,50,60,38,6,False,NaN
779,709,Trevenant,Ghost,Grass,474,85,110,76,65,82,56,6,False,NaN
780,710,PumpkabooAverage Size,Ghost,Grass,335,49,66,70,44,55,51,6,False,NaN
781,710,PumpkabooSmall Size,Ghost,Grass,335,44,66,70,44,55,56,6,False,NaN
782,710,PumpkabooLarge Size,Ghost,Grass,335,54,66,70,44,55,46,6,False,NaN
783,710,PumpkabooSuper Size,Ghost,Grass,335,59,66,70,44,55,41,6,False,NaN
784,711,GourgeistAverage Size,Ghost,Grass,494,65,90,122,58,75,84,6,False,NaN
785,711,GourgeistSmall Size,Ghost,Grass,494,55,85,122,58,75,99,6,False,NaN
786,711,GourgeistLarge Size,Ghost,Grass,494,75,95,122,58,75,69,6,False,NaN
787,711,GourgeistSuper Size,Ghost,Grass,494,85,100,122,58,75,54,6,False,NaN
788,712,Bergmite,Ice,NaN,304,55,69,85,32,35,28,6,False,NaN
789,713,Avalugg,Ice,NaN,514,95,117,184,44,46,28,6,False,NaN
790,714,Noibat,Flying,Dragon,245,40,30,35,45,40,55,6,False,NaN
791,715,Noivern,Flying,Dragon,535,85,70,80,97,80,123,6,False,NaN
792,716,Xerneas,Fairy,NaN,680,126,131,95,131,98,99,6,True,NaN
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True,NaN
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True,NaN
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,NaN
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,NaN
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,NaN
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,NaN
799,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,Flamer,True

In [58]:
#aggregate statistics
#group by mean and sort values can also do sum(), count()
df.groupby(['Type 1']).mean().sort_values('Defense', ascending = False)

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,
Steel,442.851852,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148
Rock,392.727273,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909
Dragon,474.375000,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000
Ground,356.281250,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000
Ghost,486.500000,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500
Water,303.089286,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714
Ice,423.541667,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,3.541667,0.083333
Grass,344.871429,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,3.357143,0.042857
Bug,334.492754,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,3.217391,0.000000
Dark,461.354839,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516
Poison,251.785714,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,2.535714,0.000000
Fire,327.403846,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,3.211538,0.096154
Psychic,380.807018,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,3.385965,0.245614
Electric,363.500000,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,3.272727,0.090909
Flying,677.750000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000
Fighting,363.851852,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,3.370370,0.000000
Fairy,449.529412,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,4.117647,0.058824
Normal,319.173469,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,3.051020,0.020408

In [59]:
df['count'] = 1

df.groupby(['Type 1', 'Type 2']).count()['count']

Type 1    Type 2
Bug       Electric     2
          Fighting     2
          Fire         2
          Flying      14
          Ghost        1
          Grass        6
          Ground       2
          Poison      12
          Rock         3
          Steel        7
          Water        1
Dark      Dragon       3
          Fighting     2
          Fire         3
          Flying       5
          Ghost        2
          Ice          2
          Psychic      2
          Steel        2
Dragon    Electric     1
          Fairy        1
          Fire         1
          Flying       6
          Ground       5
          Ice          3
          Psychic      4
Electric  Dragon       1
          Fairy        1
          Fire         1
          Flying       5
                      ..
Rock      Fighting     1
          Flying       4
          Grass        2
          Ground       6
          Ice          2
          Psychic      2
          Steel        3
          Water        6
Steel     Dragon       1
          Fairy        3
          Fighting     1
          Flying       1
          Ghost        4
          Ground       2
          Psychic      7
          Rock         3
Water     Dark         6
          Dragon       2
          Electric     2
          Fairy        2
          Fighting     3
          Flying       7
          Ghost        2
          Grass        3
          Ground      10
          Ice          3
          Poison       3
          Psychic      5
          Rock         4
          Steel        1
Name: count, Length: 136, dtype: int64

In [62]:
#large dataset loading
new_df = pd.DataFrame(columns = df.columns)

for df in pd.read_csv('pokemon_data.csv', chunksize = 5):
    results = df.groupby(['Type 1']).count()
    
    new_df = pd.concat([new_df, results])
#loads DF but in chunks of 5

new_df

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:7: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  import sys

,#,Attack,Defense,Generation,HP,Legendary,Name,Sp. Atk,Sp. Def,Speed,Type 1,Type 2
Fire,1,1,1,1,1,1,1,1,1,1,NaN,0
Grass,4,4,4,4,4,4,4,4,4,4,NaN,4
Fire,4,4,4,4,4,4,4,4,4,4,NaN,3
Water,1,1,1,1,1,1,1,1,1,1,NaN,0
Bug,2,2,2,2,2,2,2,2,2,2,NaN,0
Water,3,3,3,3,3,3,3,3,3,3,NaN,0
Bug,5,5,5,5,5,5,5,5,5,5,NaN,5
Normal,5,5,5,5,5,5,5,5,5,5,NaN,4
Normal,3,3,3,3,3,3,3,3,3,3,NaN,2
Poison,2,2,2,2,2,2,2,2,2,2,NaN,0
Electric,2,2,2,2,2,2,2,2,2,2,NaN,0
Ground,2,2,2,2,2,2,2,2,2,2,NaN,0
Poison,1,1,1,1,1,1,1,1,1,1,NaN,0
Poison,5,5,5,5,5,5,5,5,5,5,NaN,2
Fairy,2,2,2,2,2,2,2,2,2,2,NaN,0
Fire,2,2,2,2,2,2,2,2,2,2,NaN,0
Normal,1,1,1,1,1,1,1,1,1,1,NaN,1
Grass,2,2,2,2,2,2,2,2,2,2,NaN,2
Normal,1,1,1,1,1,1,1,1,1,1,NaN,1
Poison,2,2,2,2,2,2,2,2,2,2,NaN,2
Bug,4,4,4,4,4,4,4,4,4,4,NaN,4
Grass,1,1,1,1,1,1,1,1,1,1,NaN,1
Ground,2,2,2,2,2,2,2,2,2,2,NaN,0
Normal,2,2,2,2,2,2,2,2,2,2,NaN,0
Water,1,1,1,1,1,1,1,1,1,1,NaN,0
Fighting,2,2,2,2,2,2,2,2,2,2,NaN,0
Fire,2,2,2,2,2,2,2,2,2,2,NaN,0
Water,1,1,1,1,1,1,1,1,1,1,NaN,0
Psychic,2,2,2,2,2,2,2,2,2,2,NaN,0
Water,3,3,3,3,3,3,3,3,3,3,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...
Psychic,3,3,3,3,3,3,3,3,3,3,NaN,0
Steel,2,2,2,2,2,2,2,2,2,2,NaN,2
Fairy,3,3,3,3,3,3,3,3,3,3,NaN,0
Steel,2,2,2,2,2,2,2,2,2,2,NaN,2
Dark,2,2,2,2,2,2,2,2,2,2,NaN,2
Fairy,1,1,1,1,1,1,1,1,1,1,NaN,0
Rock,2,2,2,2,2,2,2,2,2,2,NaN,2
Electric,1,1,1,1,1,1,1,1,1,1,NaN,1
Poison,2,2,2,2,2,2,2,2,2,2,NaN,2
Water,2,2,2,2,2,2,2,2,2,2,NaN,0
Electric,1,1,1,1,1,1,1,1,1,1,NaN,1
Rock,4,4,4,4,4,4,4,4,4,4,NaN,4
Dragon,1,1,1,1,1,1,1,1,1,1,NaN,0
Electric,1,1,1,1,1,1,1,1,1,1,NaN,1
Fairy,1,1,1,1,1,1,1,1,1,1,NaN,0
Fighting,1,1,1,1,1,1,1,1,1,1,NaN,1
Rock,1,1,1,1,1,1,1,1,1,1,NaN,1
Dragon,2,2,2,2,2,2,2,2,2,2,NaN,0
Ghost,2,2,2,2,2,2,2,2,2,2,NaN,2
Steel,1,1,1,1,1,1,1,1,1,1,NaN,1
Ghost,5,5,5,5,5,5,5,5,5,5,NaN,5
Ghost,3,3,3,3,3,3,3,3,3,3,NaN,3
Ice,2,2,2,2,2,2,2,2,2,2,NaN,0
Dark,1,1,1,1,1,1,1,1,1,1,NaN,1
Dragon,1,1,1,1,1,1,1,1,1,1,NaN,1
Fairy,1,1,1,1,1,1,1,1,1,1,NaN,0
Flying,2,2,2,2,2,2,2,2,2,2,NaN,2
Fire,1,1,1,1,1,1,1,1,1,1,NaN,1
Psychic,2,2,2,2,2,2,2,2,2,2,NaN,2
Rock,2,2,2,2,2,2,2,2,2,2,NaN,2